### ISSUE TITLE
Jax's Unique Tailwind

### ISSUE THREAD

**Issue by lilypog** [lilypog/GokuRomHackRedux#1]
Jax's E supplements the original "Give the next move priority" idea by instead doubling Jax's speed for the turn following a successful hit. This is done currently with existing tailwind code, but as such it bundles in a message meant to indicate when tailwind is over. We need to basically replicate tailwind code without this message, tag this new effect with a different name, and apply _that_ effect to Jax's E instead of tailwind.

**Comment by lilypog** [comment]
For reference, see **..\PBS\moves.txt line 8751** for move description (under tag COUNTERSTRIKE) and **..\Data\Scripts\011_Battle\003_Move\009_MoveEffects_MultiHit.rb line 691** for move programming. I don't know where to find the tailwind effect at the moment but I'm sure it wouldn't be difficult to figure out.

**Comment by kassarole** [comment]
Move effects are defined in [../Data/Scripts/011_Battle/0007_Other battle code/001_PBEffects.rb](https://github.com/lilypog/GokuRomHackRedux/blob/main/Pokemon%20Essentials%20v21.1%202023-07-30/Data/Scripts/011_Battle/007_Other%20battle%20code/001_PBEffects.rb)

**Comment by kassarole** [comment]
The message comes from [..\Data\Scripts\011_Battle\001_Battle\011_Battle_EndOfRoundPhase.rb](https://github.com/lilypog/GokuRomHackRedux/blob/main/Pokemon%20Essentials%20v21.1%202023-07-30/Data/Scripts/011_Battle/001_Battle/011_Battle_EndOfRoundPhase.rb)

**Comment by kassarole** [comment]
The actual move code appears to be in [..\Data\Scripts\011_Battle\003_Move\006_MoveEffects_BattlerStats.rb](https://github.com/lilypog/GokuRomHackRedux/blob/main/Pokemon%20Essentials%20v21.1%202023-07-30/Data/Scripts/011_Battle/003_Move/006_MoveEffects_BattlerStats.rb)

**Comment by kassarole** [comment]
Calling JaxWind
